#!/bin/bash
set -o pipefail  # trace ERR through pipes
set -o errtrace  # trace ERR through 'time command' and other functions
set -o nounset   ## set -u : exit the script if you try to use an uninitialised variable
set -o errexit   ## set -e : exit the script if any statement returns a non-true return value

# Clear files (reduce snapshot size)
yum clean all

rm -rf /var/cache/yum/* /tmp/*

if [ -d "/usr/lib/python2.7" ];then
	find "/usr/lib/python2.7/" -type f | grep .pyc | awk '{system("rm -f "$1)}'
fi
